### ISSUE TITLE
Duplicate project references?

### ISSUE THREAD

**Issue by stusherwin** [configit-open-source/csmerge#3]
Just did a rebase using CsMerge and there seem to be duplicate references now to dlls brought in by NuGet packages:

Warnings in Visual Studio:
![image](https://cloud.githubusercontent.com/assets/606984/8616645/e84e400e-26f4-11e5-86d3-b5298d36bb36.png)

Project file:
![image](https://cloud.githubusercontent.com/assets/606984/8616689/37ddfb3c-26f5-11e5-9cc4-c18a59621ba2.png)

Awesome tool though - happy to manually delete the extra references for now, it's so much better than the merge conflict hell there was before.

**Comment by Scott-Harris** [comment]
This has been resolved, the application will now auto resolve duplicates that are identical, and ask the user to choose a resolution otherwise.
